// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// unisort
Rcpp::NumericMatrix unisort(Rcpp::NumericMatrix x);
RcppExport SEXP _runibic_unisort(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(unisort(x));
    return rcpp_result_gen;
END_RCPP
}
// calculateLCS
Rcpp::NumericMatrix calculateLCS(Rcpp::NumericVector m, Rcpp::NumericVector n);
RcppExport SEXP _runibic_calculateLCS(SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateLCS(m, n));
    return rcpp_result_gen;
END_RCPP
}
// cluster
int cluster(Rcpp::IntegerMatrix discreteInput, Rcpp::IntegerVector scores, Rcpp::IntegerVector geneOne, Rcpp::IntegerVector geneTwo, int rowNumber, int colNumber);
RcppExport SEXP _runibic_cluster(SEXP discreteInputSEXP, SEXP scoresSEXP, SEXP geneOneSEXP, SEXP geneTwoSEXP, SEXP rowNumberSEXP, SEXP colNumberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type discreteInput(discreteInputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type geneOne(geneOneSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type geneTwo(geneTwoSEXP);
    Rcpp::traits::input_parameter< int >::type rowNumber(rowNumberSEXP);
    Rcpp::traits::input_parameter< int >::type colNumber(colNumberSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster(discreteInput, scores, geneOne, geneTwo, rowNumber, colNumber));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_runibic_unisort", (DL_FUNC) &_runibic_unisort, 1},
    {"_runibic_calculateLCS", (DL_FUNC) &_runibic_calculateLCS, 2},
    {"_runibic_cluster", (DL_FUNC) &_runibic_cluster, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_runibic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
