# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computing the indexes of j-th smallest values of each row
#'
#' This function sorts separately each row of a numeric matrix and returns a matrix
#' in which the value in i-th row and j-th column represent the index of the j-th smallest value of the i-th row.
#'
#' @param x a numeric matrix
#' @return a numeric matrix with indexes indicating positions of j-th smallest element in each row
#'
#' @examples
#' A=matrix(c(4,3,1,2,5,8,6,7),nrow=2,byrow=TRUE)
#' unisort(A)
#'
#' @export
unisort <- function(x) {
    .Call('_runibic_unisort', PACKAGE = 'runibic', x)
}

#' Calculating Longest Common Subsequence (LCS) between two numeric vectors
#'
#' This function calculates using dynamic programming the Longest Common Subsequence (LCS)
#' between two numeric vectors.
#'
#' @param m a numeric vector
#' @param n a numeric vector
#' @return a matrix storing Longest Common Subsequence (LCS)
#'
#' @examples
#' calculateLCS(c(1,2,3,4,5),c(1,2,4))
#'
#' @export
calculateLCS <- function(m, n) {
    .Call('_runibic_calculateLCS', PACKAGE = 'runibic', m, n)
}

